$('.owl-carousel-1').owlCarousel({
                loop:true,
                margin:10,
                rtl:false,
                dots:true,
                autoplay:true,
                autoplayTimeout:6050,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                    },
                    600:{
                        items:1,
                    },
                    1000:{
                        items:1,
                        loop:true
                    }
                }
            })

            $('.owl-carousel-2').owlCarousel({
                loop:true,
                margin:10,
                rtl:true,
                dots:true,
                autoplay:true,
                autoplayTimeout:6100,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                    },
                    600:{
                        items:1,
                    },
                    1000:{
                        items:1,
                        loop:true
                    }
                }
            })

            $('.owl-carousel-3').owlCarousel({
                loop:true,
                margin:10,
                rtl:false,
                dots:true,
                autoplay:true,
                autoplayTimeout:6150,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                    },
                    600:{
                        items:1,
                    },
                    1000:{
                        items:1,
                        loop:true
                    }
                }
            })

            $('.owl-carousel-4').owlCarousel({
                loop:true,
                margin:10,
                rtl:true,
                dots:true,
                autoplay:true,
                autoplayTimeout:6200,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                    },
                    600:{
                        items:1,
                    },
                    1000:{
                        items:1,
                        loop:true
                    }
                }
            })

            $('.owl-carousel-parceiros').owlCarousel({
                loop:true,
                margin:10,
                dots:true,
                autoplay:true,
                autoWidth:true,
                autoplayTimeout:2000,
            })